name: buildit
channels:
  - defaults
dependencies:
  - python=3.10.8
  - libffi=3.3
  - pip
  - wheel
  - setuptools
  - readline
  - ncurses
  - zlib
  - sqlite
  - tk
  - xz
  - pip:
    - backcall==0.2.0
    - celery[redis]==5.2.7
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - decorator==5.1.0
    - flask==2.3.2
    - flask-cors==3.0.10
    - fonttools==4.28.4
    - gunicorn==20.1.0
    - gym==0.22.0
    - importlib-metadata==4.8.2
    - ipython==7.30.1
    - jedi==0.18.1
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - networkx==2.6.3
    - numpy==1.24.3
    - packaging==21.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prompt-toolkit==3.0.24
    - ptyprocess==0.7.0
    - pyglet==1.5.23
    - pygments==2.10.0
    - pyparsing==3.0.6
    - pyquaternion==0.9.9
    - python-dateutil==2.8.2
    - python-fcl==0.7.0.4
    - requests==2.27.1
    - rtree==0.9.7
    - scikit-learn==1.0.2
    - scipy==1.10.1
    - six==1.16.0
    - sortedcontainers==2.4.0
    - tqdm==4.62.3
    - traitlets==5.1.1
    - trimesh==3.10.8
    - typing-extensions==4.0.1
    - wcwidth==0.2.5
    - zipp==3.6.0
